# Generated by Django 2.2.12 on 2023-02-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0002_auto_20230206_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
